version: '3.8'
services:
  java-staging:
    image: my-java-app
    container_name: java-staging
    ports:
      - "8081:8080"
    networks:
      - my-network
    restart: always
    build: .

networks:
  my-network:
    driver: bridge
